services:
  billing_db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file: 
    - path: ./.env
      required: true # default
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./src/sql/db_dump.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    env_file: 
    - path: ./.env
      required: true # default
    build:
      context:    ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "${SERVER_ADDRESS}:8000"
    depends_on:
      - billing_db
