services:
  billing_db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./src/sql/db_dump.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
    build:
      context:    ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "${SERVER_ADDRESS}:8000"
    depends_on:
      - billing_db
